m=Map("softwarecenter",translate("网站管理"),translate("正常运行ONMP后先添加名称再选择要安装的应用软件"))
m:section(SimpleSection).template = "softwarecenter/website_status"
s = m:section(TypedSection,"website")
s.addremove = true
a = s:option(Flag,"website_enabled",translate("Enabled"),translate("请确保服务器已正常运行"))
a = s:option(Flag,"autodeploy_enable",translate("启用自动部署"))
a:depends("website_enabled",1)
a = s:option(ListValue,"website_select",translate("website"),translate("请选择你需要部署的网站"))
a:value("0","tz（雅黑PHP探针）")
a:value("1","phpMyAdmin（数据库管理工具）")
a:value("2","WordPress（使用最广泛的CMS）")
a:value("3","Owncloud（经典的私有云）")
a:value("4","Nextcloud（Owncloud团队的新作，美观强大的个人云盘）")
a:value("5","h5ai（优秀的文件目录）")
a:value("6","Lychee（一个很好看，易于使用的Web相册）")
a:value("7","Kodexplorer（可道云aka芒果云在线文档管理器）")
a:value("8","Typecho (流畅的轻量级开源博客程序)")
a:value("9","Z-Blog (体积小，速度快的PHP博客程序)")
a:value("10","DzzOffice (开源办公平台)")
a:depends("autodeploy_enable",1)
a = s:option(Flag,"redis_enabled",translate("启用Redis"),translate("只有Owncloud和Nextcloud才可以使用。<br>需要先在web界面配置完成后，才能使用开启Redis"))
a:depends("website_select","3")
a:depends("website_select","4")
a = s:option(Flag,"customdeploy_enabled",translate("启用自定义部署"))
a:depends("autodeploy_enable",0)
a = s:option(Value,"website_dir",translate("网站目录"),translate("该目录自动创建在/opt/wwwroot/下，只需输入目录名"))
a:depends("customdeploy_enabled",1)
a = s:option(Value,"port",translate("访问端口设定"),translate("如设定的端口已在用，系统自动找查80-99中可用的端口"))
a:value("",translate("自动获取"))
a:depends("website_enabled",1)
return m