# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for password hack deny by wulishui
LUCI_DEPENDS:=+gawk +ipset +ip6tables
LUCI_PKGARCH:=all
PKG_VERSION:=v6.0.5
PKG_RELEASE:=20210314

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


