#!/bin/sh /etc/rc.common
# Author: wulishui <wulishui@gmail.com>

START=99
USE_PROCD=1

start_instance() {
	procd_open_instance
	procd_set_param command /etc/cowbping.sh 
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	stop_service
	enabled=$(uci get cowbping.cowbping.enabled 2>/dev/null)
	if [ "$enabled" == 1 ]; then
	  [ -f /etc/config/cbp_cmd ] || touch /etc/config/cbp_cmd
	  start_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger 'cowbping'
}

stop_service() {
	kill -9 $(busybox ps -w | grep 'cbp_cmd'| grep -v 'grep' | awk '{print $1}') >/dev/null 2>&1
}

restart() {
	stop_service
	start_service
}

