#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@PwdHackDeny[-1]
	add ucitrack PwdHackDeny
	set ucitrack.@PwdHackDeny[-1].init=PwdHackDeny
	commit ucitrack
EOF
echo "/etc/WEBbadip.log" >>/etc/sysupgrade.conf
echo "/etc/SSHbadip.log" >>/etc/sysupgrade.conf
echo "/etc/PwdHackDeny/" >>/etc/sysupgrade.conf

uci delete firewall.PwdHackDeny
uci set firewall.PwdHackDeny=include
uci set firewall.PwdHackDeny.type=script
uci set firewall.PwdHackDeny.path=/etc/PwdHackDenysh.include
uci commit firewall

rm -f /tmp/luci-indexcache
exit 0
