#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cowbbonding[-1]
	add ucitrack cowbbonding
	set ucitrack.@cowbbonding[-1].init=cowbbonding
	commit ucitrack
EOF

        echo "/etc/cowbbonding/list.cfg" >> /etc/sysupgrade.conf

rm -f /tmp/luci-indexcache
exit 0
