#
# Copyright (C) 2019 Jianpeng Xiang (1505020109@mail.hnust.edu.cn)
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDIR)/rules.mk
PKG_NAME:=luci-app-softwarecenter
LUCI_TITLE:=LuCI Support for Software Center
LUCI_DEPENDS:=+softwarecenter
PKG_VERSION:=1.0.6

PKG_MAINTAINER:=Jianpeng Xiang <1505020109@mail.hnust.edu.cn>
PKG_LICENSE:=GPLv3

$(eval $(call BuildPackage,$(PKG_NAME)))
