#!/bin/bash /etc/rc.common
# wulishui 20200216-20200603 v4.2.4
# Author: wulishui <wulishui@gmail.com> , all rights reserved.

START=95

config_host() {
cat>>/tmp/cowbbonding/dhcp<<EOF
config host
	option name '$name'
	option dns '1'
	option mac '$MAC'
	option ip '$IP'
	option leasetime '$leasetime'

EOF
}

mac_ip_err() {
    E1=`cat /tmp/cowbbonding/list.added |egrep -o "(-$MAC-)"|wc -l` ; E2=`cat /tmp/cowbbonding/list.added |egrep -o "(-$IP-)" |wc -l` ; EXT=""
    [ -z "$MAC" ] && EXT="---MAC地址？ 请修正---"
    [ -z "$IP" ] && EXT="---IP地址？ 请修正---"
    [ -z "$MAC" -a -z "$IP" ] && EXT="---MAC、IP地址？ 请修正---"
    [ "$E1" -gt 0 ] || echo ""$line" "$EXT"" >> /tmp/cowbbonding/list.cfg_
}

chk_list() {
    E1=`cat /tmp/cowbbonding/list.added |egrep -o "(-$MAC-)"|wc -l` ; E2=`cat /tmp/cowbbonding/list.added |egrep -o "(-$IP-)" |wc -l` ; EXT=""
    [ "$E1" == 0 -a "$E2" == 0 ] && [ "$work_mode" == "1" -o "$work_mode" == "2" ] && config_host
    [ "$E1" == 0 -a "$E2" == 0 ] && [ "$work_mode" == "2" -o "$work_mode" == "3" ] && ip neigh add $IP lladdr $MAC nud permanent dev $interface 2>/dev/null
    [ "$E1" == 0 -a "$E2" == 0 ] && [ "$work_mode" == "2" -a "$whitelistenabled" == 1 ] && iptables -A cowbbonding -m mac --mac-source $MAC -s $IP -j ACCEPT 2>/dev/null
    [ "$E1" -gt 0 ] && echo "1" >> /tmp/cowbbonding/EXT.mac # EXT="---MAC有重复，丢弃！---"
    [ "$E2" -gt 0 ] && echo "1" >> /tmp/cowbbonding/EXT.ip && EXT="---IP有重复，请修正！---" 
    [ -z "$name" -a -z "$exname" ] && name=""
    [ -z "$name" -a -n "$exname" ] && name=""$exname" ---hostname错误，请修正---"
    [ "$E1" -gt 0 ] || echo ""$MAC" "$IP" "$name" "$EXT"" >> /tmp/cowbbonding/list.cfg_
#    [ "$E1" -gt 0 -o "$E2" -gt 0 ] || echo "-"$MAC"-"$IP"-" >> /tmp/cowbbonding/list.added
}

smart_mode() {
cat /tmp/cowbbonding/list.cfg 2>/dev/null|sed '/^'[#!/]'/d'|sed '/^ *$/d'|tee /tmp/cowbbonding/list.cfg_org |while read line
do
   MAC=`echo $line |egrep -o "([A-Fa-f0-9]{2}[:-]){5}[A-Fa-f0-9]{2}"|tr '[a-z]' '[A-Z]'|sed 's/-/:/g'|head -1`
   IP=`echo $line |egrep -o "(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])"|head -1`
   exname=`echo $line |sed 's/ /\n/g'|grep -v ':'|egrep -v "([A-Fa-f0-9]{2}[:-]){5}[A-Fa-f0-9]{2}"|egrep "(^[a-zA-Z])"|egrep "([a-zA-Z0-9]$)"|sed '/^ *$/d'|head -1`
   chk_name=`echo $exname |sed 's/\t*/\n/g'|sed '/^ *$/d'|egrep -v "([A-Z]|[a-z]|[0-9]|[._-])"|sed '/[A-Za-z0-9._-]/d'|sed '/^ *$/d'|wc -l`
   [ ! "$chk_name" -gt 0 ] && name="$exname" || name=""
   [ -n "$MAC" -a -n "$IP" ] && chk_list
   [ -z "$MAC" -o -z "$IP" ] && mac_ip_err
done
}

flush_arp() {
  ip link set arp off dev "$interface"
  ip link set arp on dev "$interface"
# ip neigh flush dev "$interface"
}

flush_dhcp() {
sum=`grep -c 'config host' /etc/config/dhcp`
	for i in $(seq 1 $sum)
	do
	 uci del dhcp.@host[]
	done
uci commit dhcp
}

pre_mac_whitelist() {
[ "$work_mode" == "2" -a "$whitelistenabled" == 1 ] || return
EXT1=`uci get firewall.@defaults[0].SWOBL_INPUT 2>/dev/null` || EXT1=0
EXT2=`uci get firewall.@defaults[0].SWOBL_FORWARD 2>/dev/null` || EXT2=0
if [ "$EXT1" == 0 -a "$EXT2" == 0 ]; then
uci set firewall.@defaults[0].SWOBL_FORWARD=1
uci commit firewall
/etc/init.d/firewall reload >/dev/null 2>&1
fi
iptables -N cowbbonding 2>/dev/null || iptables -F cowbbonding 2>/dev/null
iptables -C SWOBL -j cowbbonding 2>/dev/null || iptables -A SWOBL -j cowbbonding 2>/dev/null
}

post_mac_whitelist() {
[ "$work_mode" == "2" -a "$whitelistenabled" == 1 ] || return
#iptables -A cowbbonding -m mac --mac-source $MAC -d $IP -j ACCEPT 2>/dev/null
iptables -A cowbbonding -j REJECT
if [ -f /etc/config/guestwifi/guest_del ]; then
interface_ip=$(grep '# interface_ip' /etc/config/guestwifi/guest_del 2>/dev/null| awk -F ' ' '{print $3}')
DEV=$(ip route show 2>/dev/null | grep "$interface_ip" |grep 'wlan'|awk -F ' ' '{print $3}')
IP=`echo "$interface_ip"|awk -F '.' '{print $1"."$2"."$3".1/24"}'`
iptables -I cowbbonding -s $IP -o $DEV -j RETURN 2>/dev/null
#iptables -I cowbbonding -d $IP -i $DEV -j RETURN 2>/dev/null
fi
pgrep 'cowbbonding.sh' >/dev/null || /etc/cowbbonding.sh &
}

manual_add() {
sum=`grep -c 'config manual' /etc/config/cowbbonding`
[ "$sum" -gt 0 ] || return
 for i in $(seq 0 $(expr $sum - 1))
 do
  MAC=`uci get cowbbonding.@manual[$i].MAC 2>/dev/null`
  IP=`uci get cowbbonding.@manual[$i].IP 2>/dev/null`
  hostname=`uci get cowbbonding.@manual[$i].hostname 2>/dev/null`
  echo ""$MAC" "$IP" "$hostname"" >> /tmp/cowbbonding/list.cfg
  uci del cowbbonding.@manual[]
 done
 echo "" >> /tmp/cowbbonding/list.cfg
 uci commit cowbbonding
}

start(){
pgrep 'cowbbonding.sh' >/dev/null && kill -9 $(pgrep 'cowbbonding.sh') 2>/dev/null
iptables -D SWOBL -j cowbbonding 2>/dev/null
iptables -F cowbbonding 2>/dev/null

enabled=`uci get cowbbonding.cowbbonding.enabled 2>/dev/null`
[ -s /etc/cowbbonding/list.cfg ] && [ "$enabled" == 1 ] || exit 0

[ -d /tmp/cowbbonding ] && rm -f /tmp/cowbbonding/* || mkdir /tmp/cowbbonding

cp -f /etc/cowbbonding/list.cfg /tmp/cowbbonding/list.cfg
echo "" >> /tmp/cowbbonding/list.cfg #避免末行无换行符导致被丢弃

work_mode=`uci get cowbbonding.cowbbonding.work_mode 2>/dev/null`
interface=`uci get cowbbonding.cowbbonding.interface 2>/dev/null` || interface=br-lan
leasetime=`uci get cowbbonding.cowbbonding.leasetime 2>/dev/null`
whitelistenabled=`uci get cowbbonding.cowbbonding.macwhitelist 2>/dev/null`

[ "$work_mode" == 1 ] && uci set cowbbonding.cowbbonding.enabled=0 && uci commit cowbbonding

ERR=`echo "$leasetime"|sed 's/\t*/\n/g'|sed '/^ *$/d'|egrep -v "([dhinfinite]|[0-9])"|wc -l`
[ -z "$leasetime" -o "$leasetime" = "0" -o "$ERR" -gt 0 ] && leasetime="infinite"

echo "" > /tmp/cowbbonding/dhcp
echo "" > /tmp/cowbbonding/list.added
echo "" > /tmp/cowbbonding/list.cfg_org

manual_add
pre_mac_whitelist
flush_dhcp
flush_arp
smart_mode
post_mac_whitelist

ORG=`cat /tmp/cowbbonding/list.cfg_org 2>/dev/null|sed '/^ *$/d'|wc -l`
BND=`cat /tmp/cowbbonding/dhcp 2>/dev/null|grep 'config host'|sed '/^ *$/d'|wc -l`
REPmac=`cat /tmp/cowbbonding/EXT.mac 2>/dev/null|sed '/^ *$/d'|wc -l`
REip=`cat /tmp/cowbbonding/EXT.ip 2>/dev/null|sed '/^ *$/d'|wc -l`

[ "$REPmac" -gt 0 ] && echo "# $(date +"%Y-%m-%d %H:%M:%S") ------！！！！！有重复的MAC条目"$REPmac"条，已自动清除！！！！！------" >> /tmp/cowbbonding/list.cfg_ex
[ "$REip" -gt 0 ] && echo "# $(date +"%Y-%m-%d %H:%M:%S") ------！！！！！有错误，有重复的IP 条目"$REip"条，需要手动改正！！！！！------" >> /tmp/cowbbonding/list.cfg_ex
echo "# $(date +"%Y-%m-%d %H:%M:%S") ------已运行，设定条目"$ORG"条，成功绑定"$BND"条------" >> /tmp/cowbbonding/list.cfg_ex
echo "" >> /tmp/cowbbonding/list.cfg_ex

cat /tmp/cowbbonding/list.cfg_ >> /tmp/cowbbonding/list.cfg_ex

OK3=`cat /tmp/cowbbonding/list.cfg_ 2>/dev/null|sed '/^ *$/d'|wc -l`
OK4=`cat /tmp/cowbbonding/list.cfg_ex 2>/dev/null|sed '/^'[#!/]'/d'|sed '/^ *$/d'|wc -l`
[ "$OK3" -gt 0 -a "$OK4" -gt 0 ] && cp -f /tmp/cowbbonding/list.cfg_ex  /etc/cowbbonding/list.cfg

OK1=`cat /tmp/cowbbonding/dhcp|sed '/^ *$/d'|wc -l` 
[ "$OK1" -gt 5 ] && cat /tmp/cowbbonding/dhcp >> /etc/config/dhcp && /etc/init.d/dnsmasq reload 2>/dev/null

OK2=`cat /etc/cowbbonding/list.cfg 2>/dev/null|sed '/^'[#!/]'/d'|sed '/^ *$/d'|wc -l`
[ "$OK2" -gt 0 ] || cp -f /tmp/cowbbonding/list.cfg /etc/cowbbonding/list.cfg

rm -f /tmp/cowbbonding/* 2>/dev/null
}

stop(){
kill -9 $(pgrep 'cowbbonding.sh') 2>/dev/null
iptables -F cowbbonding 2>/dev/null
iptables -D SWOBL -j cowbbonding 2>/dev/null
iptables -D cowbbonding 2>/dev/null
}

restart() {
stop 
start
}



